04/02/2024 03:45:49 PM Updated user: devang 04/02/2024 03:45:49 PM - INFO - Updated user: devang
04/02/2024 03:45:49 PM Retrieved user: devang 04/02/2024 03:45:49 PM - INFO - Retrieved user: devang
04/02/2024 03:45:49 PM Added user: u2 04/02/2024 03:45:49 PM - INFO - Added user: u2
04/02/2024 03:58:24 PM Updated user: devang 04/02/2024 03:58:24 PM - INFO 
04/02/2024 03:58:24 PM Retrieved user: devang 04/02/2024 03:58:24 PM - INFO 
04/02/2024 03:58:24 PM Updated email for user: u2 is u232@gmail.com 04/02/2024 03:58:24 PM - INFO 
04/02/2024 03:58:24 PM Added user: abcd 04/02/2024 03:58:24 PM - INFO 
04/02/2024 03:58:24 PM Added user: test 04/02/2024 03:58:24 PM - INFO 
04/02/2024 03:58:35 PM Updated user: devang 04/02/2024 03:58:35 PM - INFO 
04/02/2024 03:58:35 PM Retrieved user: devang 04/02/2024 03:58:35 PM - INFO 
04/02/2024 03:58:35 PM Updated email for user: u2 is u232@gmail.com 04/02/2024 03:58:35 PM - INFO 
04/02/2024 03:58:35 PM Error adding user: abcd. Error: (mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry 'abcd' for key 'users.username'
[SQL: INSERT INTO users (username, email, full_name, created_at, updated_at) VALUES (%(username)s, %(email)s, %(full_name)s, %(created_at)s, %(updated_at)s)]
[parameters: {'username': 'abcd', 'email': 'a@gmail.com', 'full_name': 'aa cd', 'created_at': datetime.datetime(2024, 4, 2, 10, 28, 35, 659376, tzinfo=datetime.timezone.utc), 'updated_at': datetime.datetime(2024, 4, 2, 10, 28, 35, 659485, tzinfo=datetime.timezone.utc)}]
(Background on this error at: https://sqlalche.me/e/20/gkpj) 04/02/2024 03:58:35 PM - ERROR 
04/02/2024 03:58:35 PM Error adding user: test. Error: (mysql.connector.errors.IntegrityError) 1062 (23000): Duplicate entry 'test' for key 'users.username'
[SQL: INSERT INTO users (username, email, full_name, created_at, updated_at) VALUES (%(username)s, %(email)s, %(full_name)s, %(created_at)s, %(updated_at)s)]
[parameters: {'username': 'test', 'email': 'test@gmail.com', 'full_name': 'testing', 'created_at': datetime.datetime(2024, 4, 2, 10, 28, 35, 659376, tzinfo=datetime.timezone.utc), 'updated_at': datetime.datetime(2024, 4, 2, 10, 28, 35, 659485, tzinfo=datetime.timezone.utc)}]
(Background on this error at: https://sqlalche.me/e/20/gkpj) 04/02/2024 03:58:35 PM - ERROR 
2024-04-02 16:56:39,091 Updated user: devang 2024-04-02 16:56:39,091 - INFO 
2024-04-02 16:56:39,093 Retrieved user: devang 2024-04-02 16:56:39,093 - INFO 
2024-04-02 16:56:39,100 Added user: hello 2024-04-02 16:56:39,100 - INFO 
2024-04-02 17:10:23,297 Updated user: devang 2024-04-02 17:10:23,297 - INFO 
2024-04-02 17:10:23,299 Retrieved user: devang 2024-04-02 17:10:23,299 - INFO 
2024-04-02 17:10:23,306 Added user: test1 2024-04-02 17:10:23,306 - INFO 
